# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='numberOfNights',
            field=models.IntegerField(default=0),
        ),
    ]
