# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saveToDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phoneNumber', models.PositiveIntegerField()),
                ('checkIn', models.DateField()),
            ],
        ),
    ]
